version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: listen
    versions:
    - 3.5.0
  - dependency-name: bootsnap
    versions:
    - 1.7.0
    - 1.7.1
  - dependency-name: capybara
    versions:
    - 3.35.3
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
