puts "東方同人音楽流通(Apple Music)"
puts "総アルバム数: #{Discography.touhou_doujin.count}枚 (※ただし、オリジナルのみ含む)"
puts "総曲数: #{Discography.touhou_doujin.sum(:track_count)}曲 (※ただし、オリジナル含む)"
puts "東方アルバム数: #{Discography.touhou.count}枚"
puts "東方楽曲数: #{Song.touhou.count}曲"
puts "東方歌詞あり楽曲数: #{Song.touhou.has_lyrics.count}曲"
puts "Apple Music非提供楽曲: #{Song.touhou.not_streamable.count}曲"